// webrtcConnection/functions/Recorder.tsx
import {useState, useEffect} from 'react';
import {sendOffer} from './requests';
import {conn} from './store';

let webrtc: RTCPeerConnection;
let dataChannel: RTCDataChannel;
let stream: MediaStream;
let recordingStartTime: Date | null = null;
let elapsedTime: string = '00:00';

const [ans, setAns] = useState<any[]>([]);

export async function createOutboundConnection(token: string) {
  // Implementation of createOutboundConnection depends on the library used for WebRTC in React Native
  // You'll need to use a library like react-native-webrtc and follow its documentation
}

export function handleStart() {
  // Your logic for handling the start event
}

export function handleStop() {
  webrtc.close();
  stream.getTracks().forEach(track => track.stop());
  setAns([]);
  recordingStartTime = null;
  elapsedTime = '00:00';
}

export function updateElapsedTime() {
  if (recordingStartTime) {
    const now = new Date();
    const diff = now.getTime() - recordingStartTime.getTime();
    const seconds = Math.floor(diff / 1000) % 60;
    const minutes = Math.floor(diff / 60000);
    elapsedTime = `${minutes.toString().padStart(2, '0')}:${seconds
      .toString()
      .padStart(2, '0')}`;
    setTimeout(updateElapsedTime, 1000);
  }
}

// screens/backendConnections/Recorder.svelte
<script lang="ts">
  import {connection, updateState} from './store';
  import {get} from 'svelte/store';
  import {createoutboundconnection} from './webrtc';
  import {ans} from './store';

  let webrtc: RTCPeerConnection;
  let dataChannel: RTCDataChannel;
  let stream: MediaStream;
  let recordingStartTime: Date | null = null;
  let elapsedTime: string = '00:00';

  async function handleStart() {
    if (get(connection).backendAvailable) {
      stream = await navigator.mediaDevices.getUserMedia({
        audio: true,
      });

      [webrtc, dataChannel] = await createoutboundconnection(
        get(connection).token,
        stream,
      );

      dataChannel.onopen = () => {
        dataChannel.onmessage = event => {
          console.log('We received a message: ', event.data);
          const messageObject = JSON.parse(event.data);
          const threshold = 0.5;

          ans.update(currentMessages => {
            if (currentMessages.length > 0) {
              const lastCurrentMessage =
                currentMessages[currentMessages.length - 1];

              if (
                Math.abs(messageObject.start - lastCurrentMessage.start) <
                threshold
              ) {
                // Consider the messages the same if they start within the threshold
                return [...currentMessages.slice(0, -1), messageObject];
              } else if (messageObject.start < lastCurrentMessage.start) {
                // Discard the messageObject if it starts earlier than the last current message
                return currentMessages;
              }
            }
            // Add the new message if there are no previous messages or if it starts later
            return [...currentMessages, messageObject];
          });
        };
      };
      updateState({webrtc: true});
      recordingStartTime = new Date();
      updateElapsedTime();
    }
  }

  function handleStop() {
    webrtc.close();
    stream.getTracks().forEach(track => track.stop());
    ans.set([]);
    recordingStartTime = null;
    elapsedTime = '00:00';
  }

  function updateElapsedTime() {
    if (recordingStartTime) {
      const now = new Date();
      const diff = now.getTime() - recordingStartTime.getTime();
      const seconds = Math.floor(diff / 1000) % 60;
      const minutes = Math.floor(diff / 60000);
      elapsedTime = `${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
      setTimeout(updateElapsedTime, 1000);
    }
  }
</script>
